### ISSUE TITLE
Set up lookup.ld4l.org to keep historical data

### ISSUE THREAD

**Issue by zimeon** [LD4P/ld4p2-cornell#1]
See:  https://github.com/cul-it/qa_server/issues/33

This proposes adding a section that shows historical failures and statistics for failures to answer questions like...

number of failing days out of # of days run
number type of failures... can't load authority vs. exception vs. no data returned
for a given authority, did all tests fail or just a few?
are tests failing for a particular subauthority?
are tests failing for a particular type (search vs. term)

**Comment by zimeon** [comment]
2018-08-02 Changing what and how data is stored, still work to surface in UI. Won't worry about old data but have this going forward. Also doing some work on performance data

**Comment by elrayle** [comment]
Moved to repository where work will be done: https://github.com/LD4P/qa_server/issues/1
