### ISSUE TITLE
Archive ld4l-labs/qa_server and associated repos, import into ld4p organization for continued work

### ISSUE THREAD

**Issue by zimeon** [LD4P/ld4p2-cornell#10]
Archive qa-server and associated repos in ld4l-labs organization and import into ld4p organization, will add message saying the new dev happening in new place. Suggest to Dave that he work on a new fork of `ld4l_services` into the ld4p repo

**Comment by elrayle** [comment]
Moved ld4l-labs/qa_server to LD4P/qa_server_app
Moved ld4l-labs/linked_data_authorities to LD4P/linked_data_authorities

Archived both in ld4l-labs.
