### ISSUE TITLE
Reflect Music Cataloger feedback to Discogs Mapping

### ISSUE THREAD

**Issue by sfolsom** [LD4P/ld4p2-cornell#17]
Update https://github.com/LD4P/ld4p2-cornell/blob/master/Sinatra/Discogs/annotated_sinatra.json ttl annotations reflect feedback.

**Comment by zimeon** [comment]
Made updates to clarify entity types https://github.com/LD4P/ld4p2-cornell/commit/cafdb7733ca27945b5a13a700b74af0c0f1eabd5#diff-f3bad7dc2b2d6dcf6c2f9b21e434c01d
