### ISSUE TITLE
Run query for each discogs id in spreadsheet and compile big document with JSON results

### ISSUE THREAD

**Issue by zimeon** [LD4P/ld4p2-cornell#7]
Run a query on each discogs id in the spreadsheet and compile a big document of JSON results for Jason to review. Goal of this review will be to understand whether the data returned might be useful for creating starter-records in the cataloging of these 45s

**Comment by tworrall** [comment]
Jason has his JSON file.

**Comment by zimeon** [comment]
Tim ran a set of curl statements to get data from discogs, offered to remove some of the info about audit and sales/offers but Jason was happy to keep that. Had to put sleep of 3s in order not to get 503 rate limit (was being done without an account key, that is required only for search)
